#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

python -u extract_continuous.py "$@"

python -u extract_spikes.py "$@"



