#!/usr/bin/env bash
set -e

git clone https://github.com/int-brain-lab/iblenv

cd iblenv

pip install -r requirements.txt --upgrade

pip install -U --no-cache-dir -U --ignore-installed wavpack-numcodecs==0.1.3 numba==0.56.3 neo==0.11.1 probeinterface==0.2.13 spikeinterface[full,widgets]==0.96.0